name: Download Artifact

on:
  push:
    branches:
      - main

jobs:
  download_artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: webapp
        path: .

    - name: List files
      run: ls -l    

