name: Machine Image
env:
  DB_USER: ${{ secrets.DB_GCP_USER }}
  DB_DATABASE: ${{ secrets.DB_GCP_DATABASE }}
  DB_PASSWORD: ${{ secrets.DB_GCP_PASSWORD }}
  DB_HOST: ${{ secrets.DB_GCP_HOST }}
# on:
#   push:
#     branches: [ "main" ]
on: [push, pull_request]

    
jobs:
    gcloud-cli-setup:
      runs-on: ubuntu-latest
      steps:
          - id: 'auth'
            uses: 'google-github-actions/auth@v2'
            with:
             credentials_json: '${{ secrets.GCP_DEV_KEY }}'
          - name: 'Set up Cloud SDK'
            uses: 'google-github-actions/setup-gcloud@v2'
  
          - name: 'Use gcloud CLI'
            run: 'gcloud info'

        #   - name: Create Instance Template
        #     run: |
        #         gcloud compute instance-templates create instance-cli-2 \
        #         --project=devproj-414701 \
        #         --machine-type=e2-medium \
        #         --network-interface=network-tier=PREMIUM,subnet=webapp \
        #         --instance-template-region=us-east1 \
        #         --maintenance-policy=MIGRATE \
        #         --provisioning-model=STANDARD \
        #         --service-account=service-account-1@devproj-414701.iam.gserviceaccount.com \
        #         --scopes=https://www.googleapis.com/auth/cloud-platform \
        #         --region=us-east1 \
        #         --tags=allow-health-check,http-server,https-server,lb-health-check \
        #         --create-disk=auto-delete=yes,boot=yes,device-name=instance-template-20240407-234656,image=projects/devproj-414701/global/images/custom-app-image,mode=rw,size=100,type=pd-balanced \
        #         --metadata=startup-script='#!/bin/bash
        #           if [ ! -f "/home/centos/.env" ]; then
        #             sudo touch /home/centos/.env
        #           fi
        #           sudo echo "DB_HOST=${{ secrets.DB_GCP_HOST }}" > /home/centos/.env
        #           sudo echo "DB_USER=${{ secrets.DB_GCP_USER }}" >> /home/centos/.env
        #           sudo echo "DB_PASSWORD=${{ secrets.DB_GCP_PASSWORD }}" >> /home/centos/.env
        #           sudo echo "DB_DATABASE=${{ secrets.DB_GCP_DATABASE }}" >> /home/centos/.env'

        #   - name: Set Instance Template for Managed Instance Group
        #     run: |
        #       gcloud compute instance-groups managed set-instance-template web-instance-group-manager \
        #         --project=devproj-414701 \
        #         --region=us-east1 \
        #         --template=projects/devproj-414701/regions/us-east1/instanceTemplates/instance-cli-2

        #   - name: Start Rolling Update
        #     run: |
        #           gcloud compute instance-groups managed rolling-action start-update web-instance-group-manager \
        #             --project=devproj-414701 \
        #             --type=proactive \
        #             --version=template=projects/devproj-414701/regions/us-east1/instanceTemplates/instance-cli-2 \
        #             --region=us-east1

        #   - name: Check Version Target Reached
        #     run: |
        #          gcloud compute instance-groups managed wait-until web-instance-group-manager \
        #          --version-target-reached \
        #          --region=us-east1