name: Machine Image
env:
  DB_USER: ${{ secrets.DB_USER }}
  DB_DATABASE: ${{ secrets.DB_DATABASE }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_HOST: ${{ secrets.DB_HOST }}
on:
  push:
    branches: [ "main" ]
    
jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Install  and start MySQL
        run: |
         # sudo apt-get update
         sudo apt-get install -y mysql-server
         sudo systemctl start mysql.service
   
      - name: Connect to MySQL and create database
        run: |
         sudo mysql --user=${{ secrets.DB_USER }} --password=${{ secrets.DB_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_DATABASE }};"
          
      - name: Check Node.js and npm versions
        run: |
          node --version
          npm --version
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          
      - name: Run tests
        run: |
          sudo mkdir -p /var/log/webapp
          sudo touch /var/log/webapp/app.log
          sudo chmod a+w /var/log/webapp/app.log
          npm test

      - name: Checkout
        uses: actions/checkout@v2

      - name: zip application
        run: |
         zip -r webapp.zip .

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 1.8.6
        
      - name: Initial Setup
        run: |
          packer init ./Packer/packer.pkr.hcl

      - name: Run Packer Configuration for Image Creation
        id: extract_image_name
        run: |
          packer_output=$(packer build -var 'GCP_DEV_KEY=${{ secrets.GCP_DEV_KEY }}' ./Packer/packer.pkr.hcl)
          echo $packer_output
          image_name=$(echo $packer_output | sed -n "s/^.*A disk image was created in the '\([^']\+\)' project: \([^ ]\+\).*$/\2/p")
          echo $image_name
          echo "::set-output name=image_name::$image_name"

      - name: Set up gcloud CLI
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_DEV_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
  
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Create Instance Template
        run: |
                echo ${{ steps.extract_image_name.outputs.image_name }}
                echo ${{ secrets.KEY_RING }}
                echo ${{ secrets.VM_KEY }}
                gcloud compute instance-templates create instance-template${{ steps.extract_image_name.outputs.image_name }} \
                --project=${{ secrets.PROJECT }} \
                --machine-type=e2-medium \
                --network-interface=network-tier=PREMIUM,subnet=webapp \
                --instance-template-region=${{ secrets.REGION }} \
                --maintenance-policy=MIGRATE \
                --provisioning-model=STANDARD \
                --service-account=${{ secrets.SERVICE_ACC }} \
                --scopes=https://www.googleapis.com/auth/cloud-platform \
                --region=${{ secrets.REGION }} \
                --tags=allow-health-check,http-server,https-server,lb-health-check \
                --create-disk=auto-delete=yes,boot=yes,image=projects/${{ secrets.PROJECT }}/global/images/${{ steps.extract_image_name.outputs.image_name }},kms-key=projects/${{ secrets.PROJECT }}/locations/${{ secrets.REGION }}/keyRings/${{ secrets.KEY_RING }}/cryptoKeys/${{ secrets.VM_KEY }},mode=rw,size=100,type=pd-balanced \
                --metadata=startup-script='#!/bin/bash
                  if [ ! -f "/home/centos/.env" ]; then
                    sudo touch /home/centos/.env
                  fi
                  sudo echo "DB_HOST=${{ secrets.DB_GCP_HOST }}" > /home/centos/.env
                  sudo echo "DB_USER=${{ secrets.DB_GCP_USER }}" >> /home/centos/.env
                  sudo echo "DB_PASSWORD=${{ secrets.DB_GCP_PASSWORD }}" >> /home/centos/.env
                  sudo echo "DB_DATABASE=${{ secrets.DB_GCP_DATABASE }}" >> /home/centos/.env'

      - name: Set Instance Template for Managed Instance Group
        run: |
              gcloud compute instance-groups managed set-instance-template ${{ secrets.GROUP_MANAGER }}  \
                --project=${{ secrets.PROJECT }} \
                --region=${{ secrets.REGION }} \
                --template=projects/${{ secrets.PROJECT }}/regions/${{ secrets.REGION }}/instanceTemplates/instance-template${{ steps.extract_image_name.outputs.image_name }}

      - name: Start Rolling Update
        run: |
                  gcloud compute instance-groups managed rolling-action start-update ${{ secrets.GROUP_MANAGER }} \
                    --project=${{ secrets.PROJECT }} \
                    --type=proactive \
                    --version=template=projects/${{ secrets.PROJECT }}/regions/${{ secrets.REGION }}/instanceTemplates/instance-template${{ steps.extract_image_name.outputs.image_name }} \
                    --region=${{ secrets.REGION }}

      - name: Check Version Target Reached
        run: |
                 gcloud compute instance-groups managed wait-until ${{ secrets.GROUP_MANAGER }} \
                 --version-target-reached \
                 --region=${{ secrets.REGION }}
