name: Machine Image

on: [push, pull_request]


jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: zip application
        run: |
         zip -r webapp.zip .
         ls
        run: |
         zip -r webapp.zip .

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 1.8.6
        
      - name: Initial Setup
        run: |
          packer init ./Packer/packer.pkr.hcl

      - name: Run Packer Configuration for Image Creation
        run: |
             packer build -var 'GCP_DEV_KEY= ${{ secrets.GCP_DEV_KEY }}' ./Packer/packer.pkr.hcl
