name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-as2:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    outputs:
      job-status: ${{ steps.job-status.outputs.status }}

    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test