# on: push
# jobs:
#   build-node:
#     runs-on: ubuntu-latest
#     steps:
#       - run: node --version
#       - run: npm --version
#       - uses: actions/checkout@v3
#       - run: npm install
#       - run: node server.js

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    outputs:
      job-status: ${{ steps.job-status.outputs.status }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Start development server in the background
      run: npm start 

    - name: Stop background server
      if: ${{ always() }}
      run: pkill -f "npm start"

  close-workflow:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Set job status
      id: set-job-status
      run: echo "::set-output name=status::${{ needs.build-and-test.outputs.job-status }}"

    - name: Complete workflow
      if: ${{ needs.build-and-test.outputs.job-status == 'success' }}
      run: echo "Workflow completed successfully."
