name: Packer Formatting Check

on: [pull_request]


jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 1.8.6
        
      - name: Initial Setup
        run: |
          cd Packer
          packer init .

      - name: zip application
        run: zip -r webapp.zip .

      - name: Check Packer Formatting
        run: |
           if packer fmt -check ./Packer/packer.pkr.hcl; then
            echo "Packer files are formatted correctly."
           else
            echo "Packer files are not formatted correctly."
            exit 1  # Fail the workflow
           fi
      - name: Validate Packer Configuration
        run: |
             if packer validate -var 'GCP_DEV_KEY= ${{ secrets.GCP_DEV_KEY }}' ./Packer/packer.pkr.hcl; then
               echo "Packer configuration is valid."
             else
               echo "Packer configuration is not valid."
               exit 1  # Fail the workflow
             fi      