name: MySQL Setup and Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: webappforkenv

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}
          MYSQL_USER: ${{ secrets.DB_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_HOST: ${{ secrets.DB_HOST }}
        
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Wait for MySQL to start 1
        run: echo "Username is ${{ secrets.DB_USERNAME }}"
      - name: Wait for MySQL to start
        run: |
          echo "Waiting for MySQL to start..."
          sleep 20
          
      - name: Check Node.js and npm versions
        run: |
          node --version
          npm --version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test
