name: MySQL Setup and Test
env:
  DB_USER: ${{ secrets.DB_USER }}
  DB_DATABASE: ${{ secrets.DB_DATABASE }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_HOST: ${{ secrets.DB_HOST }}

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install MySQL
        run: |
         # sudo apt-get update
         sudo apt-get install -y mysql-server
         sudo systemctl start mysql.service

      # - name: Configure MySQL
      #   run: |
      #    sudo mysql --user=root --password=root
      #   #  "ALTER USER 'root'@'localhost' IDENTIFIED BY '${{ secrets.DB_PASSWORD }}'";
      #   #  "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_DATABASE }};"
   
      - name: Connect to MySQL and create database
        run: |
         sudo mysql --user=${{ secrets.DB_USER }} --password=${{ secrets.DB_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_DATABASE }};"
          
      - name: Check Node.js and npm versions
        run: |
          node --version
          npm --version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test
