name: MySQL Setup and Test
env:
  DB_USER: 'root'
  DB_DATABASE: 'database1'
  DB_PASSWORD: 'root'
  DB_HOST: 'localhost'
  MYSQL_ROOT_PASSWORD: 'root'
  MYSQL_DATABASE: 'database1'
  MYSQL_PASSWORD: 'root'
  MYSQL_HOST: 'localhost'

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    # services:
    #   mysql:
    #     image: mysql:8.0
    #     ports:
    #       - 3306:3306
    #     env:
    #       MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
    #       MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}
    #       MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
    #       MYSQL_HOST: ${{ secrets.DB_HOST }}
        
        # options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Install MySQL
        run: |
         # sudo apt-get update
         sudo apt-get install -y mysql-server
         sudo systemctl start mysql.service

      # - name: Configure MySQL
      #   run: |
      #    sudo mysql --user=root --password=root
      #   #  "ALTER USER 'root'@'localhost' IDENTIFIED BY '${{ secrets.DB_PASSWORD }}'";
      #   #  "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_DATABASE }};"
   
      - name: Connect to MySQL and create database
        run: |
         sudo mysql --user=root --password=root -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_DATABASE }};"
          
      - name: Check Node.js and npm versions
        run: |
          node --version
          npm --version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test
